apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - dev.cluster.info
  secretName: selfsigned-cert-tls
  issuerRef:
    # TODO rename this
    name: test-selfsigned