apiVersion: v1
kind: Namespace
metadata:
  # TODO rename this
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  # TODO rename this
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}