apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: exp
  template:
    metadata:
      labels:
        app: exp
    spec:
      containers:
        - name: exp
          image: strm/helloworld-http
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: exp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30019