apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: exp
  template:
    metadata:
      labels:
        app: exp
    spec:
      containers:
        - name: exp
          image: nginxdemos/hello
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: exp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: exp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30019