apiVersion: v1
kind: ConfigMap
metadata:
  name: onepassword-connect-operator-config
  namespace: default
data:
  WATCH_NAMESPACE: default
  OPERATOR_NAME: onepassword-connect-operator
  OP_CONNECT_HOST: http://onepassword-connect-service:8081
  POLLING_INTERVAL: 10
  AUTO_RESTART: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
  namespace: default
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      name: onepassword-connect-operator
  template:
    metadata:
      labels:
        name: onepassword-connect-operator
    spec:
      serviceAccountName: onepassword-connect-operator
      containers:
        - name: onepassword-connect-operator
          image: 1password/onepassword-operator:1.5
          command: ["/manager"]
          envFrom:
            configMapRef:
              name: onepassword-connect-operator-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onepassword
                  key: token