apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
        - name: setup
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              chown -R 200:200 /nexus-data &&
              cat /secret-certs/key | base64 -d > /certs/key-decoded &&
              cat /secret-certs/cert | base64 -d > /certs/cert-decoded &&
              openssl pkcs12 -export -out /certs/nexus.p12 -inkey /certs/key-decoded -in /certs/cert-decoded
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data-volume
            - mountPath: /secret-certs
              name: nexus-secret-certs-volume
            - mountPath: /certs
              name: nexus-certs-volume
#            - mountPath: /nexus-jetty
#              name: nexus-jetty-volume
      containers:
        - name: nexus
          image: %NEXUS_IMAGE%
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data-volume
#            - mountPath: /opt/sonatype/nexus/etc/jetty/
#              name: nexus-jetty-volume
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8081
#              scheme: HTTPS
#            initialDelaySeconds: 10
#            periodSeconds: 600
      volumes:
        - name: nexus-data-volume
          hostPath:
            path: /opt/kubernetes/data/nexus/data
        - name: nexus-secret-certs-volume
          secret:
            secretName: craigmiller160-tls-certs
        - name: nexus-certs-volume
          emptyDir: {}

#        - name: nexus-jetty-volume
#          hostPath:
#            path: /opt/kubernetes/data/nexus/jetty

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: standard
      port: 8081
      targetPort: 8081
      nodePort: 30003
      protocol: TCP
    - name: docker-http
      port: 8083
      targetPort: 8083
      nodePort: 30004
      protocol: TCP